### ISSUE TITLE
geen meldingen

### ISSUE THREAD

**Issue by futtta** [futtta/boekenjagerbot#6]
is de afgelopen dagen één en ander weggelegd in Lokeren, zit ook in de boekenzoeker, maar heb geen melding gekregen. draait de cronned job nog? iets anders mis?

**Comment by thunderbug** [comment]
Mijn test server staat uit, wegens verhuizen van computers naar een andere kamer. Voor de rest werkt het ok

**Comment by thunderbug** [comment]
Alles is terug in orde
